Preambel = `<pre>
   GeoImageViewer - Image Viewer linked to Maps
   Version 0.2 for HTML-browsers

   Copyright (C) 2021 - Helmut Dersch  der@hs-furtwangen.de
   
   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  </pre>
   
   <p><a href="https://hdersch.github.io">Project page</a> with documentation,
   examples and download.
   `;
var BitStream=function(){var l=[0,1,3,7,15,31,63,127,255],k=function(a,h,d,b){if(!(a instanceof ArrayBuffer))throw"Error! BitArray constructed with an invalid ArrayBuffer object";this.bytes=new Uint8Array(a,d||0,b||a.byteLength);this.bitsRead_=this.bitPtr=this.bytePtr=0;this.peekBits=h?this.peekBits_rtl:this.peekBits_ltr};k.prototype.getNumBitsRead=function(){return this.bitsRead_};k.prototype.getNumBitsLeft=function(){return 8*(this.bytes.byteLength-this.bytePtr-1)+(8-this.bitPtr)};k.prototype.peekBits_ltr=
function(a,h){var d=parseInt(a,10),b=d;if(a!==b||0>=b)return 0;a=this.bytes;for(var e=this.bytePtr,c=this.bitPtr,f=0,g=0;0<b&&!(e>=a.length);){var m=8-c;if(b>=m)f|=(a[e]&l[m]<<c)>>c<<g,e++,c=0,g+=m,b-=m;else{f|=(a[e]&l[b]<<c)>>c<<g;c+=b;break}}h&&(this.bitPtr=c,this.bytePtr=e,this.bitsRead_+=d);return f};k.prototype.peekBits_rtl=function(a,h){var d=parseInt(a,10),b=d;if(a!==b||0>=b)return 0;a=this.bytes;for(var e=this.bytePtr,c=this.bitPtr,f=0;0<b&&!(e>=a.length);){var g=8-c;if(b>=g)f<<=g,f|=l[g]&
a[e],e++,c=0,b-=g;else{f<<=b;g=8-b-c;f|=(a[e]&l[b]<<g)>>g;c+=b;break}}h&&(this.bitPtr=c,this.bytePtr=e,this.bitsRead_+=d);return f};k.prototype.getBits=function(){return((this.bytes[this.bytePtr]&255)<<16)+((this.bytes[this.bytePtr+1]&255)<<8)+(this.bytes[this.bytePtr+2]&255)>>>8-this.bitPtr&65535};k.prototype.readBits=function(a){return this.peekBits(a,!0)};k.prototype.peekBytes=function(a,h){var d=parseInt(a,10);if(a!==d||0>d)throw"Error!  Called peekBytes() with a non-positive integer: "+a;if(0===
d)return new Uint8Array;for(;0!=this.bitPtr;)this.readBits(1);a=this.getNumBitsLeft()/8;if(d>a)throw"Error!  Overflowed the bit stream! n="+d+", bytePtr="+this.bytePtr+", bytes.length="+this.bytes.length+", bitPtr="+this.bitPtr;h=h||!1;a=new Uint8Array(d);for(var b=this.bytes,e=this.bytePtr,c=d;0<c;){var f=Math.min(c,b.length-e);a.set(b.subarray(e,e+f),d-c);e+=f;if(e>=b.length)break;c-=f}h&&(this.bytePtr+=d,this.bitsRead_+=8*d);return a};k.prototype.readBytes=function(a){return this.peekBytes(a,!0)};
return k}();
var ByteStream=function(){var d=function(a,b,c){if(!(a instanceof ArrayBuffer))throw"Error! BitArray constructed with an invalid ArrayBuffer object";this.bytes=new Uint8Array(a,b||0,c||a.byteLength);this.pages_=[];this.bytesRead_=this.ptr=0};d.prototype.getNumBytesRead=function(){return this.bytesRead_};d.prototype.getNumBytesLeft=function(){return this.pages_.reduce(function(a,b){return a+b.length},this.bytes.byteLength-this.ptr)};d.prototype.movePointer_=function(a){this.ptr+=a;for(this.bytesRead_+=
a;this.ptr>=this.bytes.length&&0<this.pages_.length;)this.ptr-=this.bytes.length,this.bytes=this.pages_.shift()};d.prototype.peekNumber=function(a){var b=parseInt(a,10);if(a!==b||0>b)throw"Error!  Called peekNumber() with a non-positive integer";if(0===b)return 0;if(4<a)throw"Error!  Called peekNumber("+a+") but this method can only reliably read numbers up to 4 bytes long";if(this.getNumBytesLeft()<b)throw"Error!  Overflowed the byte stream while peekNumber()! n="+b+", ptr="+this.ptr+", bytes.length="+
this.getNumBytesLeft();a=0;for(var c=this.bytes,g=0,e=this.ptr,f=0;f<b;++f)a|=c[e++]<<8*f,e>=c.length&&(c=this.pages_[g++],e=0);return a};d.prototype.readNumber=function(a){var b=this.peekNumber(a);this.movePointer_(a);return b};d.prototype.peekSignedNumber=function(a){var b=this.peekNumber(a);a=Math.pow(2,8*a-1);b>=a&&(b-=2*a);return b};d.prototype.readSignedNumber=function(a){var b=this.peekSignedNumber(a);this.movePointer_(a);return b};d.prototype.peekBytes=function(a,b){var c=parseInt(a,10);if(a!==
c||0>c)throw"Error!  Called peekBytes() with a non-positive integer";if(0===c)return new Uint8Array;a=this.getNumBytesLeft();if(c>a)throw"Error!  Overflowed the byte stream during peekBytes! n="+c+", ptr="+this.ptr+", bytes.length="+this.getNumBytesLeft();a=new Uint8Array(c);for(var g=this.bytes,e=this.ptr,f=c,k=0;0<f;){var h=Math.min(f,g.length-e);a.set(g.subarray(e,e+h),c-f);e+=h;e>=g.length&&(g=this.pages_[k++],e=0);f-=h}b&&this.movePointer_(c);return a};d.prototype.readBytes=function(a){return this.peekBytes(a,
!0)};d.prototype.peekString=function(a){var b=parseInt(a,10);if(a!==b||0>b)throw"Error!  Called peekString() with a non-positive integer";if(0===b)return"";a=this.getNumBytesLeft();if(b>a)throw"Error!  Overflowed the byte stream while peekString()! n="+b+", ptr="+this.ptr+", bytes.length="+this.getNumBytesLeft();a=Array(b);for(var c=this.bytes,g=0,e=this.ptr,f=0;f<b;++f)a[f]=String.fromCharCode(c[e++]),e>=c.length&&(c=this.pages_[g++],e=0);return a.join("")};d.prototype.readString=function(a){var b=
this.peekString(a);this.movePointer_(a);return b};d.prototype.push=function(a){if(!(a instanceof ArrayBuffer))throw"Error! ByteStream.push() called with an invalid ArrayBuffer object";this.pages_.push(new Uint8Array(a));this.movePointer_(0)};d.prototype.tee=function(){var a=new d(this.bytes.buffer);a.bytes=this.bytes;a.ptr=this.ptr;a.pages_=this.pages_.slice();a.bytesRead_=this.bytesRead_;return a};return d}();
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(d){return d.raw=d};$jscomp.createTemplateTagFirstArgWithRaw=function(d,g){d.raw=g;return d};$jscomp.checkStringArgs=function(d,g,k){if(null==d)throw new TypeError("The 'this' value for String.prototype."+k+" must not be null or undefined");if(g instanceof RegExp)throw new TypeError("First argument to String.prototype."+k+" must not be a regular expression");return d+""};$jscomp.ASSUME_ES5=!1;
$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,g,k){if(d==Array.prototype||d==Object.prototype)return d;d[g]=k.value;return d};
$jscomp.getGlobal=function(d){d=["object"==typeof globalThis&&globalThis,d,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var g=0;g<d.length;++g){var k=d[g];if(k&&k.Math==Math)return k}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(d,g){var k=$jscomp.propertyToPolyfillSymbol[g];if(null==k)return d[g];k=d[k];return void 0!==k?k:d[g]};$jscomp.polyfill=function(d,g,k,l){g&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(d,g,k,l):$jscomp.polyfillUnisolated(d,g,k,l))};
$jscomp.polyfillUnisolated=function(d,g,k,l){k=$jscomp.global;d=d.split(".");for(l=0;l<d.length-1;l++){var n=d[l];if(!(n in k))return;k=k[n]}d=d[d.length-1];l=k[d];g=g(l);g!=l&&null!=g&&$jscomp.defineProperty(k,d,{configurable:!0,writable:!0,value:g})};
$jscomp.polyfillIsolated=function(d,g,k,l){var n=d.split(".");d=1===n.length;l=n[0];l=!d&&l in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var u=0;u<n.length-1;u++){var t=n[u];if(!(t in l))return;l=l[t]}n=n[n.length-1];k=$jscomp.IS_SYMBOL_NATIVE&&"es6"===k?l[n]:null;g=g(k);null!=g&&(d?$jscomp.defineProperty($jscomp.polyfills,n,{configurable:!0,writable:!0,value:g}):g!==k&&(void 0===$jscomp.propertyToPolyfillSymbol[n]&&($jscomp.propertyToPolyfillSymbol[n]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(n):
$jscomp.POLYFILL_PREFIX+n),$jscomp.defineProperty(l,$jscomp.propertyToPolyfillSymbol[n],{configurable:!0,writable:!0,value:g})))};$jscomp.polyfill("String.prototype.startsWith",function(d){return d?d:function(g,k){var l=$jscomp.checkStringArgs(this,g,"startsWith");g+="";var n=l.length,u=g.length;k=Math.max(0,Math.min(k|0,l.length));for(var t=0;t<u&&k<n;)if(l[k++]!=g[t++])return!1;return t>=u}},"es6","es3");
var Unzip=function(){function d(a){if("object"!=typeof a||1>a.length)return v("Error! getHuffmanCodes() called with an invalid array"),null;for(var p=a.length,b=[],c=1,f=0;f<p;++f){var e=a[f];if("number"!=typeof e||0>e)return v("bitLengths contained an invalid number in getHuffmanCodes(): "+e+" of type "+typeof e),null;void 0==b[e]&&(b[e]=0);0<e&&b[e]++;e>c&&(c=e)}f=[];e=0;for(var h=1;h<=c;++h){var q=h-1;void 0==b[q]&&(b[q]=0);e=e+b[h-1]<<1;f[h]=e}b={};for(e=c=0;e<p;++e)h=a[e],0!=h&&(b[f[h]]={length:h,
symbol:e},c++,f[h]++);b.maxLength=c;return b}function g(a,p){for(var b=0,c=0;;){var f=a.readBits(1);b=b<<1|f;++c;if(p.hasOwnProperty(b)&&p[b].length==c)break;if(c>p.maxLength){v("Bit stream out of sync, didn't find a Huffman Code, length was "+c+" and table only max code length of "+p.maxLength);break}}return p[b].symbol}function k(a,p,b,c){for(var f=0,e=0;;){var h=g(a,p);++f;if(256>h)c.insertByte(h),e++;else if(256==h)break;else{h=B[h-257];h=h[1]+a.readBits(h[0]);var q=C[g(a,b)],m=q[1]+a.readBits(q[0]);
q=c.ptr-m;e+=h;if(h>m)for(m=c.data;h--;)c.insertByte(m[q++]);else c.insertBytes(c.data.subarray(q,q+h))}}return e}var l=0,n=null,u=null,t=!1,r=function(a){postMessage({type:"info",msg:a})},v=function(a){postMessage({type:"error",msg:a})},D=[1,2,4,8,16,32,64,128,256,512,1024,2048,4096,8192,16384,32768],x=function(a){if("object"!=typeof a||!a.readNumber||"function"!=typeof a.readNumber)return null;a.readNumber(4);this.version=a.readNumber(2);this.generalPurpose=a.readNumber(2);this.compressionMethod=
a.readNumber(2);this.lastModFileTime=a.readNumber(2);this.lastModFileDate=a.readNumber(2);this.crc32=a.readNumber(4);this.compressedSize=a.readNumber(4);this.uncompressedSize=a.readNumber(4);this.fileNameLength=a.readNumber(2);this.extraFieldLength=a.readNumber(2);this.filename=null;0<this.fileNameLength&&(this.filename=a.readString(this.fileNameLength));this.extraField=null;0<this.extraFieldLength&&(this.extraField=a.readString(this.extraFieldLength));this.hasDataDescriptor=0!==(this.generalPurpose&
D[3]);!this.hasDataDescriptor||0===this.crc32&&0===this.compressedSize&&0===this.uncompressedSize||v("Zip local file with a data descriptor and non-zero crc/compressedSize/uncompressedSize");this.fileData=null;var p=0;if(this.hasDataDescriptor){for(var b=a.tee(),c=!1,f=0;!c;){for(;67324752!==a.peekNumber(4)&&134630224!==a.peekNumber(4)&&33639248!==a.peekNumber(4);)f++,a.readBytes(1);var e=b.peekBytes(f),h=new ByteStream(e.buffer,f-16,16);e=h.readNumber(4);var q=h.readNumber(4),m=h.readNumber(4);h=
h.readNumber(4);134695760===e?m===f-16&&(c=!0,p=16):m===f-12&&(c=!0,p=12);c&&(this.crc32=q,this.compressedSize=m,this.uncompressedSize=h)}a=b}this.fileData=new Uint8Array(a.readBytes(this.compressedSize));a.readBytes(p);t&&(r("Zip Local File Header:"),r(" version="+this.version),r(" general purpose="+this.generalPurpose),r(" compression method="+this.compressionMethod),r(" last mod file time="+this.lastModFileTime),r(" last mod file date="+this.lastModFileDate),r(" crc32="+this.crc32),r(" compressed size="+
this.compressedSize),r(" uncompressed size="+this.uncompressedSize),r(" file name length="+this.fileNameLength),r(" extra field length="+this.extraFieldLength),r(" filename = '"+this.filename+"'"),r(" hasDataDescriptor = "+this.hasDataDescriptor))};x.prototype.unzip=function(){this.fileData||v("unzip() called on a file with out compressed file data");if(0==this.compressionMethod)t&&r("ZIP v"+this.version+", store only: "+this.filename+" ("+this.compressedSize+" bytes)");else if(8==this.compressionMethod){t&&
r("ZIP v2.0, DEFLATE: "+this.filename+" ("+this.compressedSize+" bytes)");a:{var a=this.fileData;var p=this.uncompressedSize;a=new BitStream(a.buffer,!1,a.byteOffset,a.byteLength);p=new ByteBuffer(p);do{var b=a.readBits(1);var c=a.readBits(2);if(0==c){for(;0!=a.bitPtr;)a.readBits(1);c=a.readBits(16);a.readBits(16);0<c&&p.insertBytes(a.readBytes(c))}else if(1==c){if(!y){c=Array(288);for(var f=0;143>=f;++f)c[f]=8;for(f=144;255>=f;++f)c[f]=9;for(f=256;279>=f;++f)c[f]=7;for(f=280;287>=f;++f)c[f]=8;y=
d(c)}c=y;if(!z){f=Array(32);for(var e=0;32>e;++e)f[e]=5;z=d(f)}k(a,c,z,p)}else if(2==c){c=a.readBits(5)+257;f=a.readBits(5)+1;e=a.readBits(4)+4;for(var h=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],q=0;q<e;++q)h[E[q]]=a.readBits(3);h=d(h);e=[];for(q=0;e.length<c+f;){var m=g(a,h);if(15>=m)e.push(m),q=m;else if(16==m)for(m=a.readBits(2)+3;m--;)e.push(q);else if(17==m)for(m=a.readBits(3)+3;m--;)e.push(0);else if(18==m)for(m=a.readBits(7)+11;m--;)e.push(0)}c=e.splice(c,f);f=d(e);c=d(c);k(a,f,c,p)}else{v("Error! Encountered deflate block of type 3");
a=null;break a}}while(1!=b);a=p.data}this.fileData=a}else v("UNSUPPORTED VERSION/FORMAT: ZIP v"+this.version+", compression method="+(this.compressionMethod+": ")+(this.filename+" ("+this.compressedSize+" bytes)")),this.fileData=null};var y=null,z=null,E=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],B=[[0,3],[0,4],[0,5],[0,6],[0,7],[0,8],[0,9],[0,10],[1,11],[1,13],[1,15],[1,17],[2,19],[2,23],[2,27],[2,31],[3,35],[3,43],[3,51],[3,59],[4,67],[4,83],[4,99],[4,115],[5,131],[5,163],[5,195],[5,227],
[0,258]],C=[[0,1],[0,2],[0,3],[0,4],[1,5],[1,7],[2,9],[2,13],[3,17],[3,25],[4,33],[4,49],[5,65],[5,97],[6,129],[6,193],[7,257],[7,385],[8,513],[8,769],[9,1025],[9,1537],[10,2049],[10,3073],[11,4097],[11,6145],[12,8193],[12,12289],[13,16385],[13,24577]];onmessage=function(a){var p=a.data.file||a.data.bytes;t=!!a.data.logToConsole;n?n.push(p):n=new ByteStream(p);0===l&&(u=[],postMessage({type:"start"}),l=1);if(1===l||2===l)try{for(var b=n.tee();67324752==b.peekNumber(4);){var c=new x(b);c&&0<c.uncompressedSize&&
c.fileData&&(n=b.tee(),u.push(c),c.unzip(),null!=c.fileData&&postMessage({type:"extract",unarchivedFile:c}))}if(134630224==b.peekNumber(4)){t&&r(" Found an Archive Extra Data Signature");b.readNumber(4);var f=b.readNumber(4);b.readString(f)}if(33639248==b.peekNumber(4))for(t&&r(" Found a Central File Header");33639248==b.peekNumber(4);){b.readNumber(4);var e={versionMadeBy:b.readNumber(2),versionNeededToExtract:b.readNumber(2),generalPurposeBitFlag:b.readNumber(2),compressionMethod:b.readNumber(2),
lastModFileTime:b.readNumber(2),lastModFileDate:b.readNumber(2),crc32:b.readNumber(4),compressedSize:b.readNumber(4),uncompressedSize:b.readNumber(4),fileNameLength:b.readNumber(2),extraFieldLength:b.readNumber(2),fileCommentLength:b.readNumber(2),diskNumberStart:b.readNumber(2),internalFileAttributes:b.readNumber(2),externalFileAttributes:b.readNumber(4),relativeOffset:b.readNumber(4)};e.fileName=b.readString(e.fileNameLength);e.extraField=b.readString(e.extraFieldLength);e.fileComment=b.readString(e.fileCommentLength);
if(t){console.log("Central Directory File Header:");for(var h in e)console.log("  "+h+" = "+e[h])}}if(84233040==b.peekNumber(4)){t&&r(" Found a Digital Signature");b.readNumber(4);var q=b.readNumber(2);b.readString(q)}a={};if(101010256==b.peekNumber(4)){b.readNumber(4);var m={numberOfThisDisk:b.readNumber(2),diskWhereCentralDirectoryStarts:b.readNumber(2),numberOfCentralDirectoryRecordsOnThisDisk:b.readNumber(2),totalNumberOfCentralDirectoryRecords:b.readNumber(2),sizeOfCentralDirectory:b.readNumber(4),
offsetOfStartOfCentralDirectory:b.readNumber(4),commentLength:b.readNumber(2)};m.comment=b.readString(m.commentLength);if(t){console.log("End of Central Dir Signature:");for(var A in m)console.log("  "+A+" = "+m[A])}a.comment=m.comment}n=b.tee();l=3;postMessage({type:"finish",metadata:a})}catch(w){if("string"===typeof w&&w.startsWith("Error!  Overflowed"))l=2;else throw console.error("Found an error while unzipping"),console.dir(w),w;}};return x}();
var ByteBuffer=function(){var d=function(a){if("number"!=typeof a||0>=a)throw"Error! ByteBuffer initialized with '"+a+"'";this.data=new Uint8Array(a);this.ptr=0};d.prototype.insertByte=function(a){this.data[this.ptr++]=a};d.prototype.insertBytes=function(a){this.data.set(a,this.ptr);this.ptr+=a.length};d.prototype.writeNumber=function(a,b){if(1>b||!b)throw"Trying to write into too few bytes: "+b;if(0>a)throw"Trying to write a negative number ("+a+") as an unsigned number to an ArrayBuffer";if(a>Math.pow(2,
8*b)-1)throw"Trying to write "+a+" into only "+b+" bytes";for(var c=[];0<b--;)c.push(a&255),a>>=8;this.insertBytes(c)};d.prototype.writeSignedNumber=function(a,b){if(1>b)throw"Trying to write into too few bytes: "+b;var c=Math.pow(2,8*b-1);if(a>=c||a<-c)throw"Trying to write "+a+" into only "+b+" bytes";for(c=[];0<b--;)c.push(a&255),a>>=8;this.insertBytes(c)};d.prototype.writeASCIIString=function(a){for(var b=0;b<a.length;++b){var c=a.charCodeAt(b);if(0>c||255<c)throw"Trying to write a non-ASCII string!";
this.insertByte(c)}};return d}();
/*
 pako 2.0.3 https://github.com/nodeca/pako @license (MIT AND Zlib) */
!function(N,U){"object"==typeof exports&&"undefined"!=typeof module?U(exports):"function"==typeof define&&define.amd?define(["exports"],U):U((N="undefined"!=typeof globalThis?globalThis:N||self).pako={})}(this,function(N){function U(){this.mode=0;this.last=!1;this.wrap=0;this.havedict=!1;this.total=this.check=this.dmax=this.flags=0;this.head=null;this.wnext=this.whave=this.wsize=this.wbits=0;this.window=null;this.extra=this.offset=this.length=this.bits=this.hold=0;this.distcode=this.lencode=null;
this.have=this.ndist=this.nlen=this.ncode=this.distbits=this.lenbits=0;this.next=null;this.lens=new Uint16Array(320);this.work=new Uint16Array(288);this.distdyn=this.lendyn=null;this.was=this.back=this.sane=0}function T(b){var d=this.options=xa({chunkSize:65536,windowBits:15,to:""},b||{});d.raw&&0<=d.windowBits&&16>d.windowBits&&(d.windowBits=-d.windowBits,0===d.windowBits&&(d.windowBits=-15));!(0<=d.windowBits&&16>d.windowBits)||b&&b.windowBits||(d.windowBits+=32);15<d.windowBits&&48>d.windowBits&&
0==(15&d.windowBits)&&(d.windowBits|=15);this.err=0;this.msg="";this.ended=!1;this.chunks=[];this.strm=new ya;this.strm.avail_out=0;b=P.inflateInit2(this.strm,d.windowBits);if(b!==V)throw Error(ba[b]);this.header=new za;P.inflateGetHeader(this.strm,this.header);var c;if(c=d.dictionary){if("string"==typeof d.dictionary){c=d.dictionary;var m,k,h,w=c.length,x=0;for(k=0;k<w;k++){var n=c.charCodeAt(k);55296==(64512&n)&&k+1<w&&(m=c.charCodeAt(k+1),56320==(64512&m)&&(n=65536+(n-55296<<10)+(m-56320),k++));
x+=128>n?1:2048>n?2:65536>n?3:4}var q=new Uint8Array(x);for(k=h=0;h<x;k++)n=c.charCodeAt(k),55296==(64512&n)&&k+1<w&&(m=c.charCodeAt(k+1),56320==(64512&m)&&(n=65536+(n-55296<<10)+(m-56320),k++)),128>n?q[h++]=n:2048>n?(q[h++]=192|n>>>6,q[h++]=128|63&n):65536>n?(q[h++]=224|n>>>12,q[h++]=128|n>>>6&63,q[h++]=128|63&n):(q[h++]=240|n>>>18,q[h++]=128|n>>>12&63,q[h++]=128|n>>>6&63,q[h++]=128|63&n);d.dictionary=q}else"[object ArrayBuffer]"===ia.call(d.dictionary)&&(d.dictionary=new Uint8Array(d.dictionary));
c=d.raw&&(b=P.inflateSetDictionary(this.strm,d.dictionary),b!==V)}if(c)throw Error(ba[b]);}function W(b,d){d=new T(d);if(d.push(b),d.err)throw d.msg||ba[d.err];return d.result}var ca=function(b,d,c,m){var k=65535&b|0;b=b>>>16&65535|0;for(var h;0!==c;){h=2E3<c?2E3:c;c-=h;do k=k+d[m++]|0,b=b+k|0;while(--h);k%=65521;b%=65521}return k|b<<16|0},Aa=new Uint32Array(function(){for(var b,d=[],c=0;256>c;c++){b=c;for(var m=0;8>m;m++)b=1&b?3988292384^b>>>1:b>>>1;d[c]=b}return d}()),O=function(b,d,c,m){c=m+c;
for(b^=-1;m<c;m++)b=b>>>8^Aa[255&(b^d[m])];return-1^b},Ba=new Uint16Array([3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0]),Ca=new Uint8Array([16,16,16,16,16,16,16,16,17,17,17,17,18,18,18,18,19,19,19,19,20,20,20,20,21,21,21,21,16,72,78]),Da=new Uint16Array([1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577,0,0]),Ea=new Uint8Array([16,16,16,16,17,17,18,18,19,19,20,20,21,21,22,22,23,23,24,24,25,
25,26,26,27,27,28,28,29,29,64,64]),X=function(b,d,c,m,k,h,w,x){var n=x.bits,q,H,a,u,v,t,l,p,e,g=0,f,R=null,B=0,G=new Uint16Array(16);var r=new Uint16Array(16);var A,D,C=null,I=0;for(v=0;15>=v;v++)G[v]=0;for(t=0;t<m;t++)G[d[c+t]]++;var J=n;for(l=15;1<=l&&0===G[l];l--);if(J>l&&(J=l),0===l)return k[h++]=20971520,k[h++]=20971520,x.bits=1,0;for(n=1;n<l&&0===G[n];n++);J<n&&(J=n);for(v=q=1;15>=v;v++)if(q<<=1,q-=G[v],0>q)return-1;if(0<q&&(0===b||1!==l))return-1;r[1]=0;for(v=1;15>v;v++)r[v+1]=r[v]+G[v];for(t=
0;t<m;t++)0!==d[c+t]&&(w[r[d[c+t]]++]=t);if(0===b?(R=C=w,u=19):1===b?(R=Ba,B-=257,C=Ca,I-=257,u=256):(R=Da,C=Ea,u=-1),f=0,t=0,v=n,r=h,p=J,e=0,a=-1,g=1<<J,m=g-1,1===b&&852<g||2===b&&592<g)return 1;for(;;){var z=v-e;w[t]<u?(A=0,D=w[t]):w[t]>u?(A=C[I+w[t]],D=R[B+w[t]]):(A=96,D=0);q=1<<v-e;n=H=1<<p;do H-=q,k[r+(f>>e)+H]=z<<24|A<<16|D|0;while(0!==H);for(q=1<<v-1;f&q;)q>>=1;if(0!==q?(f&=q-1,f+=q):f=0,t++,0==--G[v]){if(v===l)break;v=d[c+w[t]]}if(v>J&&(f&m)!==a){0===e&&(e=J);r+=n;p=v-e;for(q=1<<p;p+e<l&&
(q-=G[p+e],!(0>=q));)p++,q<<=1;if(g+=1<<p,1===b&&852<g||2===b&&592<g)return 1;a=f&m;k[a]=J<<24|p<<16|r-h|0}}return 0!==f&&(k[r+f]=v-e<<24|4194304),x.bits=J,0},E={Z_NO_FLUSH:0,Z_PARTIAL_FLUSH:1,Z_SYNC_FLUSH:2,Z_FULL_FLUSH:3,Z_FINISH:4,Z_BLOCK:5,Z_TREES:6,Z_OK:0,Z_STREAM_END:1,Z_NEED_DICT:2,Z_ERRNO:-1,Z_STREAM_ERROR:-2,Z_DATA_ERROR:-3,Z_MEM_ERROR:-4,Z_BUF_ERROR:-5,Z_NO_COMPRESSION:0,Z_BEST_SPEED:1,Z_BEST_COMPRESSION:9,Z_DEFAULT_COMPRESSION:-1,Z_FILTERED:1,Z_HUFFMAN_ONLY:2,Z_RLE:3,Z_FIXED:4,Z_DEFAULT_STRATEGY:0,
Z_BINARY:0,Z_TEXT:1,Z_UNKNOWN:2,Z_DEFLATED:8},ja=E.Z_FINISH,Fa=E.Z_BLOCK,Z=E.Z_TREES,S=E.Z_OK,Ga=E.Z_STREAM_END,Ha=E.Z_NEED_DICT,K=E.Z_STREAM_ERROR,ka=E.Z_DATA_ERROR,la=E.Z_MEM_ERROR,Ia=E.Z_BUF_ERROR,ma=E.Z_DEFLATED,na=function(b){return(b>>>24&255)+(b>>>8&65280)+((65280&b)<<8)+((255&b)<<24)},oa=function(b){if(!b||!b.state)return K;var d=b.state;return b.total_in=b.total_out=d.total=0,b.msg="",d.wrap&&(b.adler=1&d.wrap),d.mode=1,d.last=0,d.havedict=0,d.dmax=32768,d.head=null,d.hold=0,d.bits=0,d.lencode=
d.lendyn=new Int32Array(852),d.distcode=d.distdyn=new Int32Array(592),d.sane=1,d.back=-1,S},pa=function(b){if(!b||!b.state)return K;var d=b.state;return d.wsize=0,d.whave=0,d.wnext=0,oa(b)},qa=function(b,d){var c;if(!b||!b.state)return K;var m=b.state;return 0>d?(c=0,d=-d):(c=1+(d>>4),48>d&&(d&=15)),d&&(8>d||15<d)?K:(null!==m.window&&m.wbits!==d&&(m.window=null),m.wrap=c,m.wbits=d,pa(b))},ra=function(b,d){if(!b)return K;var c=new U;b.state=c;c.window=null;d=qa(b,d);return d!==S&&(b.state=null),d},
da,ea,sa=!0,ta=function(b,d,c,m){var k;b=b.state;return null===b.window&&(b.wsize=1<<b.wbits,b.wnext=0,b.whave=0,b.window=new Uint8Array(b.wsize)),m>=b.wsize?(b.window.set(d.subarray(c-b.wsize,c),0),b.wnext=0,b.whave=b.wsize):(k=b.wsize-b.wnext,k>m&&(k=m),b.window.set(d.subarray(c-m,c-m+k),b.wnext),(m-=k)?(b.window.set(d.subarray(c-m,c),0),b.wnext=m,b.whave=b.wsize):(b.wnext+=k,b.wnext===b.wsize&&(b.wnext=0),b.whave<b.wsize&&(b.whave+=k))),0},P={inflateReset:pa,inflateReset2:qa,inflateResetKeep:oa,
inflateInit:function(b){return ra(b,15)},inflateInit2:ra,inflate:function(b,d){var c,m,k,h,w,x=0,n=new Uint8Array(4),q,H=new Uint8Array([16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15]);if(!b||!b.state||!b.output||!b.input&&0!==b.avail_in)return K;var a=b.state;12===a.mode&&(a.mode=13);var u=b.next_out;var v=b.output;var t=b.avail_out;var l=b.next_in;var p=b.input;var e=b.avail_in;var g=a.hold;var f=a.bits;var R=e;var B=t;var G=S;a:for(;;)switch(a.mode){case 1:if(0===a.wrap){a.mode=13;break}for(;16>
f;){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}if(2&a.wrap&&35615===g){a.check=0;n[0]=255&g;n[1]=g>>>8&255;a.check=O(a.check,n,2,0);f=g=0;a.mode=2;break}if(a.flags=0,a.head&&(a.head.done=!1),!(1&a.wrap)||(((255&g)<<8)+(g>>8))%31){b.msg="incorrect header check";a.mode=30;break}if((15&g)!==ma){b.msg="unknown compression method";a.mode=30;break}if(g>>>=4,f-=4,w=8+(15&g),0===a.wbits)a.wbits=w;else if(w>a.wbits){b.msg="invalid window size";a.mode=30;break}a.dmax=1<<a.wbits;b.adler=a.check=1;a.mode=512&g?10:
12;f=g=0;break;case 2:for(;16>f;){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}if(a.flags=g,(255&a.flags)!==ma){b.msg="unknown compression method";a.mode=30;break}if(57344&a.flags){b.msg="unknown header flags set";a.mode=30;break}a.head&&(a.head.text=g>>8&1);512&a.flags&&(n[0]=255&g,n[1]=g>>>8&255,a.check=O(a.check,n,2,0));f=g=0;a.mode=3;case 3:for(;32>f;){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}a.head&&(a.head.time=g);512&a.flags&&(n[0]=255&g,n[1]=g>>>8&255,n[2]=g>>>16&255,n[3]=g>>>24&255,a.check=O(a.check,
n,4,0));f=g=0;a.mode=4;case 4:for(;16>f;){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}a.head&&(a.head.xflags=255&g,a.head.os=g>>8);512&a.flags&&(n[0]=255&g,n[1]=g>>>8&255,a.check=O(a.check,n,2,0));f=g=0;a.mode=5;case 5:if(1024&a.flags){for(;16>f;){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}a.length=g;a.head&&(a.head.extra_len=g);512&a.flags&&(n[0]=255&g,n[1]=g>>>8&255,a.check=O(a.check,n,2,0));f=g=0}else a.head&&(a.head.extra=null);a.mode=6;case 6:if(1024&a.flags&&(c=a.length,c>e&&(c=e),c&&(a.head&&(w=a.head.extra_len-
a.length,a.head.extra||(a.head.extra=new Uint8Array(a.head.extra_len)),a.head.extra.set(p.subarray(l,l+c),w)),512&a.flags&&(a.check=O(a.check,p,c,l)),e-=c,l+=c,a.length-=c),a.length))break a;a.length=0;a.mode=7;case 7:if(2048&a.flags){if(0===e)break a;c=0;do w=p[l+c++],a.head&&w&&65536>a.length&&(a.head.name+=String.fromCharCode(w));while(w&&c<e);if(512&a.flags&&(a.check=O(a.check,p,c,l)),e-=c,l+=c,w)break a}else a.head&&(a.head.name=null);a.length=0;a.mode=8;case 8:if(4096&a.flags){if(0===e)break a;
c=0;do w=p[l+c++],a.head&&w&&65536>a.length&&(a.head.comment+=String.fromCharCode(w));while(w&&c<e);if(512&a.flags&&(a.check=O(a.check,p,c,l)),e-=c,l+=c,w)break a}else a.head&&(a.head.comment=null);a.mode=9;case 9:if(512&a.flags){for(;16>f;){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}if(g!==(65535&a.check)){b.msg="header crc mismatch";a.mode=30;break}f=g=0}a.head&&(a.head.hcrc=a.flags>>9&1,a.head.done=!0);b.adler=a.check=0;a.mode=12;break;case 10:for(;32>f;){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}b.adler=
a.check=na(g);f=g=0;a.mode=11;case 11:if(0===a.havedict)return b.next_out=u,b.avail_out=t,b.next_in=l,b.avail_in=e,a.hold=g,a.bits=f,Ha;b.adler=a.check=1;a.mode=12;case 12:if(d===Fa||d===Z)break a;case 13:if(a.last){g>>>=7&f;f-=7&f;a.mode=27;break}for(;3>f;){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}switch(a.last=1&g,g>>>=1,--f,3&g){case 0:a.mode=14;break;case 1:var r=a;if(sa){da=new Int32Array(512);ea=new Int32Array(32);for(h=0;144>h;)r.lens[h++]=8;for(;256>h;)r.lens[h++]=9;for(;280>h;)r.lens[h++]=
7;for(;288>h;)r.lens[h++]=8;X(1,r.lens,0,288,da,0,r.work,{bits:9});for(h=0;32>h;)r.lens[h++]=5;X(2,r.lens,0,32,ea,0,r.work,{bits:5});sa=!1}r.lencode=da;r.lenbits=9;r.distcode=ea;r.distbits=5;if(a.mode=20,d===Z){g>>>=2;f-=2;break a}break;case 2:a.mode=17;break;case 3:b.msg="invalid block type",a.mode=30}g>>>=2;f-=2;break;case 14:g>>>=7&f;for(f-=7&f;32>f;){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}if((65535&g)!=(g>>>16^65535)){b.msg="invalid stored block lengths";a.mode=30;break}if(a.length=65535&g,g=
0,f=0,a.mode=15,d===Z)break a;case 15:a.mode=16;case 16:if(c=a.length,c){if(c>e&&(c=e),c>t&&(c=t),0===c)break a;v.set(p.subarray(l,l+c),u);e-=c;l+=c;t-=c;u+=c;a.length-=c;break}a.mode=12;break;case 17:for(;14>f;){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}if(a.nlen=257+(31&g),g>>>=5,f-=5,a.ndist=1+(31&g),g>>>=5,f-=5,a.ncode=4+(15&g),g>>>=4,f-=4,286<a.nlen||30<a.ndist){b.msg="too many length or distance symbols";a.mode=30;break}a.have=0;a.mode=18;case 18:for(;a.have<a.ncode;){for(;3>f;){if(0===e)break a;
e--;g+=p[l++]<<f;f+=8}a.lens[H[a.have++]]=7&g;g>>>=3;f-=3}for(;19>a.have;)a.lens[H[a.have++]]=0;if(a.lencode=a.lendyn,a.lenbits=7,q={bits:a.lenbits},G=X(0,a.lens,0,19,a.lencode,0,a.work,q),a.lenbits=q.bits,G){b.msg="invalid code lengths set";a.mode=30;break}a.have=0;a.mode=19;case 19:for(;a.have<a.nlen+a.ndist;){for(;x=a.lencode[g&(1<<a.lenbits)-1],k=x>>>24,h=65535&x,!(k<=f);){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}if(16>h)g>>>=k,f-=k,a.lens[a.have++]=h;else{if(16===h){for(r=k+2;f<r;){if(0===e)break a;
e--;g+=p[l++]<<f;f+=8}if(g>>>=k,f-=k,0===a.have){b.msg="invalid bit length repeat";a.mode=30;break}w=a.lens[a.have-1];c=3+(3&g);g>>>=2;f-=2}else if(17===h){for(r=k+3;f<r;){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}g>>>=k;f-=k;w=0;c=3+(7&g);g>>>=3;f-=3}else{for(r=k+7;f<r;){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}g>>>=k;f-=k;w=0;c=11+(127&g);g>>>=7;f-=7}if(a.have+c>a.nlen+a.ndist){b.msg="invalid bit length repeat";a.mode=30;break}for(;c--;)a.lens[a.have++]=w}}if(30===a.mode)break;if(0===a.lens[256]){b.msg=
"invalid code -- missing end-of-block";a.mode=30;break}if(a.lenbits=9,q={bits:a.lenbits},G=X(1,a.lens,0,a.nlen,a.lencode,0,a.work,q),a.lenbits=q.bits,G){b.msg="invalid literal/lengths set";a.mode=30;break}if(a.distbits=6,a.distcode=a.distdyn,q={bits:a.distbits},G=X(2,a.lens,a.nlen,a.ndist,a.distcode,0,a.work,q),a.distbits=q.bits,G){b.msg="invalid distances set";a.mode=30;break}if(a.mode=20,d===Z)break a;case 20:a.mode=21;case 21:if(6<=e&&258<=t){b.next_out=u;b.avail_out=t;b.next_in=l;b.avail_in=e;
a.hold=g;a.bits=f;var A;e=l=void 0;var D=b,C=D.state;var I=D.next_in;v=D.input;var J=I+(D.avail_in-5);var z=D.next_out;p=D.output;var Ja=z-(B-D.avail_out);var aa=z+(D.avail_out-257);var Ka=C.dmax;var ua=C.wsize;var La=C.whave;var L=C.wnext;var Q=C.window;var y=C.hold;h=C.bits;r=C.lencode;f=C.distcode;g=(1<<C.lenbits)-1;t=(1<<C.distbits)-1;b:do{15>h&&(y+=v[I++]<<h,h+=8,y+=v[I++]<<h,h+=8);var F=r[y&g];c:for(;;){if(e=F>>>24,y>>>=e,h-=e,e=F>>>16&255,0===e)p[z++]=65535&F;else{if(!(16&e)){if(0==(64&e)){F=
r[(65535&F)+(y&(1<<e)-1)];continue c}if(32&e){C.mode=12;break b}D.msg="invalid literal/length code";C.mode=30;break b}u=65535&F;(e&=15)&&(h<e&&(y+=v[I++]<<h,h+=8),u+=y&(1<<e)-1,y>>>=e,h-=e);15>h&&(y+=v[I++]<<h,h+=8,y+=v[I++]<<h,h+=8);F=f[y&t];d:for(;;){if(e=F>>>24,y>>>=e,h-=e,e=F>>>16&255,!(16&e)){if(0==(64&e)){F=f[(65535&F)+(y&(1<<e)-1)];continue d}D.msg="invalid distance code";C.mode=30;break b}if(l=65535&F,e&=15,h<e&&(y+=v[I++]<<h,h+=8,h<e&&(y+=v[I++]<<h,h+=8)),l+=y&(1<<e)-1,l>Ka){D.msg="invalid distance too far back";
C.mode=30;break b}if(y>>>=e,h-=e,e=z-Ja,l>e){if(e=l-e,e>La&&C.sane){D.msg="invalid distance too far back";C.mode=30;break b}if(A=0,F=Q,0===L){if(A+=ua-e,e<u){u-=e;do p[z++]=Q[A++];while(--e);A=z-l;F=p}}else if(L<e){if(A+=ua+L-e,e-=L,e<u){u-=e;do p[z++]=Q[A++];while(--e);if(A=0,L<u){e=L;u-=e;do p[z++]=Q[A++];while(--e);A=z-l;F=p}}}else if(A+=L-e,e<u){u-=e;do p[z++]=Q[A++];while(--e);A=z-l;F=p}for(;2<u;)p[z++]=F[A++],p[z++]=F[A++],p[z++]=F[A++],u-=3;u&&(p[z++]=F[A++],1<u&&(p[z++]=F[A++]))}else{A=z-
l;do p[z++]=p[A++],p[z++]=p[A++],p[z++]=p[A++],u-=3;while(2<u);u&&(p[z++]=p[A++],1<u&&(p[z++]=p[A++]))}break}}break}}while(I<J&&z<aa);u=h>>3;I-=u;h-=u<<3;y&=(1<<h)-1;D.next_in=I;D.next_out=z;D.avail_in=I<J?J-I+5:5-(I-J);D.avail_out=z<aa?aa-z+257:257-(z-aa);C.hold=y;C.bits=h;u=b.next_out;v=b.output;t=b.avail_out;l=b.next_in;p=b.input;e=b.avail_in;g=a.hold;f=a.bits;12===a.mode&&(a.back=-1);break}for(a.back=0;x=a.lencode[g&(1<<a.lenbits)-1],k=x>>>24,r=x>>>16&255,h=65535&x,!(k<=f);){if(0===e)break a;
e--;g+=p[l++]<<f;f+=8}if(r&&0==(240&r)){y=k;Q=r;for(L=h;x=a.lencode[L+((g&(1<<y+Q)-1)>>y)],k=x>>>24,r=x>>>16&255,h=65535&x,!(y+k<=f);){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}g>>>=y;f-=y;a.back+=y}if(g>>>=k,f-=k,a.back+=k,a.length=h,0===r){a.mode=26;break}if(32&r){a.back=-1;a.mode=12;break}if(64&r){b.msg="invalid literal/length code";a.mode=30;break}a.extra=15&r;a.mode=22;case 22:if(a.extra){for(r=a.extra;f<r;){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}a.length+=g&(1<<a.extra)-1;g>>>=a.extra;f-=a.extra;
a.back+=a.extra}a.was=a.length;a.mode=23;case 23:for(;x=a.distcode[g&(1<<a.distbits)-1],k=x>>>24,r=x>>>16&255,h=65535&x,!(k<=f);){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}if(0==(240&r)){y=k;Q=r;for(L=h;x=a.distcode[L+((g&(1<<y+Q)-1)>>y)],k=x>>>24,r=x>>>16&255,h=65535&x,!(y+k<=f);){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}g>>>=y;f-=y;a.back+=y}if(g>>>=k,f-=k,a.back+=k,64&r){b.msg="invalid distance code";a.mode=30;break}a.offset=h;a.extra=15&r;a.mode=24;case 24:if(a.extra){for(r=a.extra;f<r;){if(0===e)break a;
e--;g+=p[l++]<<f;f+=8}a.offset+=g&(1<<a.extra)-1;g>>>=a.extra;f-=a.extra;a.back+=a.extra}if(a.offset>a.dmax){b.msg="invalid distance too far back";a.mode=30;break}a.mode=25;case 25:if(0===t)break a;if(c=B-t,a.offset>c){if(c=a.offset-c,c>a.whave&&a.sane){b.msg="invalid distance too far back";a.mode=30;break}c>a.wnext?(c-=a.wnext,m=a.wsize-c):m=a.wnext-c;c>a.length&&(c=a.length);r=a.window}else r=v,m=u-a.offset,c=a.length;c>t&&(c=t);t-=c;a.length-=c;do v[u++]=r[m++];while(--c);0===a.length&&(a.mode=
21);break;case 26:if(0===t)break a;v[u++]=a.length;t--;a.mode=21;break;case 27:if(a.wrap){for(;32>f;){if(0===e)break a;e--;g|=p[l++]<<f;f+=8}if(B-=t,b.total_out+=B,a.total+=B,B&&(b.adler=a.check=a.flags?O(a.check,v,B,u-B):ca(a.check,v,B,u-B)),B=t,(a.flags?g:na(g))!==a.check){b.msg="incorrect data check";a.mode=30;break}f=g=0}a.mode=28;case 28:if(a.wrap&&a.flags){for(;32>f;){if(0===e)break a;e--;g+=p[l++]<<f;f+=8}if(g!==(4294967295&a.total)){b.msg="incorrect length check";a.mode=30;break}f=g=0}a.mode=
29;case 29:G=Ga;break a;case 30:G=ka;break a;case 31:return la;default:return K}return b.next_out=u,b.avail_out=t,b.next_in=l,b.avail_in=e,a.hold=g,a.bits=f,(a.wsize||B!==b.avail_out&&30>a.mode&&(27>a.mode||d!==ja))&&ta(b,b.output,b.next_out,B-b.avail_out),R-=b.avail_in,B-=b.avail_out,b.total_in+=R,b.total_out+=B,a.total+=B,a.wrap&&B&&(b.adler=a.check=a.flags?O(a.check,v,B,b.next_out-B):ca(a.check,v,B,b.next_out-B)),b.data_type=a.bits+(a.last?64:0)+(12===a.mode?128:0)+(20===a.mode||15===a.mode?256:
0),(0===R&&0===B||d===ja)&&G===S&&(G=Ia),G},inflateEnd:function(b){if(!b||!b.state)return K;var d=b.state;return d.window&&(d.window=null),b.state=null,S},inflateGetHeader:function(b,d){if(!b||!b.state)return K;b=b.state;return 0==(2&b.wrap)?K:(b.head=d,d.done=!1,S)},inflateSetDictionary:function(b,d){var c=d.length,m,k,h;return b&&b.state?(m=b.state,0!==m.wrap&&11!==m.mode?K:11===m.mode&&(k=1,k=ca(k,d,c,0),k!==m.check)?ka:(h=ta(b,d,c,c),h?(m.mode=31,la):(m.havedict=1,S))):K},inflateInfo:"pako inflate (from Nodeca project)"},
xa=function(b){for(var d=Array.prototype.slice.call(arguments,1);d.length;){var c=d.shift();if(c){if("object"!=typeof c)throw new TypeError(c+"must be non-object");for(var m in c)Object.prototype.hasOwnProperty.call(c,m)&&(b[m]=c[m])}}return b},va=!0;try{String.fromCharCode.apply(null,new Uint8Array(1))}catch(b){va=!1}for(var Y=new Uint8Array(256),M=0;256>M;M++)Y[M]=252<=M?6:248<=M?5:240<=M?4:224<=M?3:192<=M?2:1;Y[254]=Y[254]=1;var ba={2:"need dictionary",1:"stream end",0:"","-1":"file error","-2":"stream error",
"-3":"data error","-4":"insufficient memory","-5":"buffer error","-6":"incompatible version"},ya=function(){this.input=null;this.total_in=this.avail_in=this.next_in=0;this.output=null;this.total_out=this.avail_out=this.next_out=0;this.msg="";this.state=null;this.data_type=2;this.adler=0},za=function(){this.os=this.xflags=this.time=this.text=0;this.extra=null;this.extra_len=0;this.comment=this.name="";this.hcrc=0;this.done=!1},ia=Object.prototype.toString,Ma=E.Z_NO_FLUSH,Na=E.Z_FINISH,V=E.Z_OK,fa=
E.Z_STREAM_END,ha=E.Z_NEED_DICT,Oa=E.Z_STREAM_ERROR,wa=E.Z_DATA_ERROR,Pa=E.Z_MEM_ERROR;T.prototype.push=function(b,d){var c=this.strm,m=this.options.chunkSize,k=this.options.dictionary,h;if(this.ended)return!1;var w=d===~~d?d:!0===d?Na:Ma;"[object ArrayBuffer]"===ia.call(b)?c.input=new Uint8Array(b):c.input=b;c.next_in=0;for(c.avail_in=c.input.length;;){0===c.avail_out&&(c.output=new Uint8Array(m),c.next_out=0,c.avail_out=m);d=P.inflate(c,w);for(d===ha&&k&&(d=P.inflateSetDictionary(c,k),d===V?d=P.inflate(c,
w):d===wa&&(d=ha));0<c.avail_in&&d===fa&&0<c.state.wrap&&0!==b[c.next_in];)P.inflateReset(c),d=P.inflate(c,w);switch(d){case Oa:case wa:case ha:case Pa:return this.onEnd(d),this.ended=!0,!1}if(h=c.avail_out,c.next_out&&(0===c.avail_out||d===fa))if("string"===this.options.to){var x=c.output;var n=c.next_out;(n=n||x.length)>x.length&&(n=x.length);for(var q=n-1;0<=q&&128==(192&x[q]);)q--;x=0>q||0===q?n:q+Y[x[q]]>n?q:n;n=c.next_out-x;var H,a,u=c.output,v=x||u.length;q=Array(2*v);for(a=H=0;a<v;){var t=
u[a++];if(128>t)q[H++]=t;else{var l=Y[t];if(4<l)q[H++]=65533,a+=l-1;else{for(t&=2===l?31:3===l?15:7;1<l&&a<v;)t=t<<6|63&u[a++],l--;1<l?q[H++]=65533:65536>t?q[H++]=t:(t-=65536,q[H++]=55296|t>>10&1023,q[H++]=56320|1023&t)}}}if(65534>H&&q.subarray&&va)q=String.fromCharCode.apply(null,q.length===H?q:q.subarray(0,H));else{a="";for(u=0;u<H;u++)a+=String.fromCharCode(q[u]);q=a}c.next_out=n;c.avail_out=m-n;n&&c.output.set(c.output.subarray(x,x+n),0);this.onData(q)}else this.onData(c.output.length===c.next_out?
c.output:c.output.subarray(0,c.next_out));if(d!==V||0!==h){if(d===fa)return d=P.inflateEnd(this.strm),this.onEnd(d),this.ended=!0,!0;if(0===c.avail_in)break}}return!0};T.prototype.onData=function(b){this.chunks.push(b)};T.prototype.onEnd=function(b){if(b===V)if("string"===this.options.to)this.result=this.chunks.join("");else{for(var d=this.chunks,c=0,m=0,k=d.length;m<k;m++)c+=d[m].length;c=new Uint8Array(c);k=m=0;for(var h=d.length;m<h;m++){var w=d[m];c.set(w,k);k+=w.length}this.result=c}this.chunks=
[];this.err=b;this.msg=this.strm.msg};M=function(b,d){return(d=d||{}).raw=!0,W(b,d)};var Qa={Inflate:T,inflate:W,inflateRaw:M,ungzip:W,constants:E};N.Inflate=T;N.constants=E;N.default=Qa;N.inflate=W;N.inflateRaw=M;N.ungzip=W;Object.defineProperty(N,"__esModule",{value:!0})});
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var m=0;m<e.length-1;m++){var p=e[m];if(!(p in d))return;d=d[p]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):
$jscomp.POLYFILL_PREFIX+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=$jscomp.checkStringArgs(this,b,"endsWith");b+="";void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}},"es6","es3");
var fillHoles=function(a){for(var b=0,c=0,d=new DataView(a.data.buffer.slice(0)),e=function(q,r){return a.data.getInt16(2*r*a.width+q,!1)},m=function(q,r){return d.getInt16(2*r*a.width+q,!1)},p=function(q,r,t){a.data.setInt16(2*r*a.width+q,t,!1)},k,l,h=0;h<a.height;h++)for(var f=0;f<a.width;f++)if(-32768==e(f,h)){for(var g=f+1;g<a.width&&-32768==e(g,h);)g++;0==f&&g==a.width?(k=l=0,b+=a.width):(k=0==f?e(g,h):e(f-1,h),l=g>=a.width?k:e(g,h),b+=g-f);l=(l-k)/(g+1-f);for(var n=0;n<g-f;n++)p(f+n,h,k+Math.round((n+
1)*l));f=g}if(0!=b){for(h=0;h<a.width;h++)for(f=0;f<a.height;f++)if(-32768==m(h,f)){for(g=f+1;g<a.height&&-32768==m(h,g);)g++;0==f&&g==a.height?(k=l=0,c+=a.height):(k=0==f?m(h,g):m(h,f-1),l=g>=a.height?k:m(h,g),c+=g-f);l=(l-k)/(g+1-f);for(n=0;n<g-f;n++)d.setInt16(2*(f+n)*a.width+h,k+Math.round((n+1)*l),!1);f=g}for(k=0;k<a.height;k++)for(l=0;l<a.width;l++)p(l,k,Math.round((e(l,k)+m(l,k))/2));console.log("Interpolated "+b+" / "+c+" points.")}},checkHoles=function(a){for(var b=0,c=0;c<a.height;c++)for(var d=
0;d<a.width;d++)-32768==a.data.getInt16(2*c*a.width+d,!1)&&b++;console.log("Found "+b+" holes")},onload=function(a,b){function c(d){console.log(d.byteOffset+"  "+d.byteLength);return d.buffer.slice(d.byteOffset,d.byteLength+d.byteOffset)}b?(a.toLowerCase().endsWith("gz")?b=c(pako.ungzip(new Uint8Array(b))):a.toLowerCase().endsWith("zip")&&(b=new Unzip(new ByteStream(b)),b.unzip(),b=c(b.fileData)),a={data:new DataView(b)},a.width=Math.round(Math.sqrt(b.byteLength/2)),a.height=a.width,a.pt_per_deg=
a.width-1,fillHoles(a),postMessage(a,[a.data.buffer])):(postMessage(null),console.log("Error loading: "+a))},load=function(a){var b=new XMLHttpRequest;b.responseType="arraybuffer";b.onload=function(){200==b.status?onload(a,b.response):(console.log("Error, status "+b.status),postMessage(null))};b.onerror=function(){console.log("Error, request failed");postMessage(null)};b.open("GET",a,!0);b.send()},onmessage=function(a){load(a.data[0])};
